### ISSUE TITLE
Midterm-review

### ISSUE THREAD

**Issue by paveldanek** [mannd00/week8#2]
Hey, I think your program looks impressive and ambitious. A script that does something useful. I yet have to think of one... However, I tried to run your script right BEFORE it prints “Is this your home?  \n” (btw., it doesn’t turn the ”\n” into line feed...), it throws an error: “line 17: /home/user: Is a directory”.

Also, when checking the status of AABackup.service, it shows as “failed”.

Then, rsync prints its options (syntax).

Please, look at it.
-Pavel.

**Comment by mannd00** [comment]
Thanks for the input!

I learned that on some systems the echo command by default does not interpret backslash escape characters. Added "echo -e " to enable it.

Service should be working now. I did break it a few times, once was intentional to prevent having 10 different services running at once.

Thanks!
